# Generated by Django 3.2.16 on 2022-10-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers_unite', '0002_auto_20221019_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
